cp "Introducing Angular DevTools-bavWOHZM6zE.mp4" "bavWOHZM6zE.mp4"
cp "Introducing Angular DevTools-bavWOHZM6zE.webm" "bavWOHZM6zE.webm"
cp "Introducing Angular DevTools-bavWOHZM6zE.en.vtt" "bavWOHZM6zE.en.vtt"
cp "Introducing Angular DevTools-bavWOHZM6zE.cn.vtt" "bavWOHZM6zE.cn.vtt"
cp "Introducing Angular DevTools-bavWOHZM6zE.tw.vtt" "bavWOHZM6zE.tw.vtt"
cp "NG0200.mp4" "CpLOm4o_FzM.mp4"
cp "NG0200.webm" "CpLOm4o_FzM.webm"
cp "NG0200.en.vtt" "CpLOm4o_FzM.en.vtt"
cp "NG0200.cn.vtt" "CpLOm4o_FzM.cn.vtt"
cp "NG0200.tw.vtt" "CpLOm4o_FzM.tw.vtt"
cp "4 Runtime Performance Optimizations-f8sA-i6gkGQ.mp4" "f8sA-i6gkGQ.mp4"
cp "4 Runtime Performance Optimizations-f8sA-i6gkGQ.webm" "f8sA-i6gkGQ.webm"
cp "4 Runtime Performance Optimizations-f8sA-i6gkGQ.en.vtt" "f8sA-i6gkGQ.en.vtt"
cp "4 Runtime Performance Optimizations-f8sA-i6gkGQ.cn.vtt" "f8sA-i6gkGQ.cn.vtt"
cp "4 Runtime Performance Optimizations-f8sA-i6gkGQ.tw.vtt" "f8sA-i6gkGQ.tw.vtt"
cp "NG8003.mp4" "fUSAg4kp2WQ.mp4"
cp "NG8003.webm" "fUSAg4kp2WQ.webm"
cp "NG8003.en.vtt" "fUSAg4kp2WQ.en.vtt"
cp "NG8003.cn.vtt" "fUSAg4kp2WQ.cn.vtt"
cp "NG8003.tw.vtt" "fUSAg4kp2WQ.tw.vtt"
cp "Introduction to Internationalization in Angular-KNTN-nsbV7M.mp4" "KNTN-nsbV7M.mp4"
cp "Introduction to Internationalization in Angular-KNTN-nsbV7M.webm" "KNTN-nsbV7M.webm"
cp "Introduction to Internationalization in Angular-KNTN-nsbV7M.en.vtt" "KNTN-nsbV7M.en.vtt"
cp "Introduction to Internationalization in Angular-KNTN-nsbV7M.cn.vtt" "KNTN-nsbV7M.cn.vtt"
cp "Introduction to Internationalization in Angular-KNTN-nsbV7M.tw.vtt" "KNTN-nsbV7M.tw.vtt"
cp "Typed Forms in Angular-L-odCf4MfJc.mp4" "L-odCf4MfJc.mp4"
cp "Typed Forms in Angular-L-odCf4MfJc.webm" "L-odCf4MfJc.webm"
cp "Typed Forms in Angular-L-odCf4MfJc.en.vtt" "L-odCf4MfJc.en.vtt"
cp "Typed Forms in Angular-L-odCf4MfJc.cn.vtt" "L-odCf4MfJc.cn.vtt"
cp "Typed Forms in Angular-L-odCf4MfJc.tw.vtt" "L-odCf4MfJc.tw.vtt"
cp "NG0201.mp4" "lAlOryf1-WU.mp4"
cp "NG0201.webm" "lAlOryf1-WU.webm"
cp "NG0201.en.vtt" "lAlOryf1-WU.en.vtt"
cp "NG0201.cn.vtt" "lAlOryf1-WU.cn.vtt"
cp "NG0201.tw.vtt" "lAlOryf1-WU.tw.vtt"
cp "NG0302.mp4" "maI2u6Sxk9M.mp4"
cp "NG0302.webm" "maI2u6Sxk9M.webm"
cp "NG0302.en.vtt" "maI2u6Sxk9M.en.vtt"
cp "NG0302.cn.vtt" "maI2u6Sxk9M.cn.vtt"
cp "NG0302.tw.vtt" "maI2u6Sxk9M.tw.vtt"
cp "NG0100.mp4" "O47uUnJjbJc.mp4"
cp "NG0100.webm" "O47uUnJjbJc.webm"
cp "NG0100.en.vtt" "O47uUnJjbJc.en.vtt"
cp "NG0100.cn.vtt" "O47uUnJjbJc.cn.vtt"
cp "NG0100.tw.vtt" "O47uUnJjbJc.tw.vtt"
cp "NG8002.mp4" "wfLkB3RsSJM.mp4"
cp "NG8002.webm" "wfLkB3RsSJM.webm"
cp "NG8002.en.vtt" "wfLkB3RsSJM.en.vtt"
cp "NG8002.cn.vtt" "wfLkB3RsSJM.cn.vtt"
cp "NG8002.tw.vtt" "wfLkB3RsSJM.tw.vtt"
cp "Getting Started with Standalone Components in Angular-x5PZwb4XurU.mp4" "x5PZwb4XurU.mp4"
cp "Getting Started with Standalone Components in Angular-x5PZwb4XurU.webm" "x5PZwb4XurU.webm"
cp "Getting Started with Standalone Components in Angular-x5PZwb4XurU.en.vtt" "x5PZwb4XurU.en.vtt"
cp "Getting Started with Standalone Components in Angular-x5PZwb4XurU.cn.vtt" "x5PZwb4XurU.cn.vtt"
cp "Getting Started with Standalone Components in Angular-x5PZwb4XurU.tw.vtt" "x5PZwb4XurU.tw.vtt"
cp "NG0300.mp4" "z_3Z5mOm59I.mp4"
cp "NG0300.webm" "z_3Z5mOm59I.webm"
cp "NG0300.en.vtt" "z_3Z5mOm59I.en.vtt"
cp "NG0300.cn.vtt" "z_3Z5mOm59I.cn.vtt"
cp "NG0300.tw.vtt" "z_3Z5mOm59I.tw.vtt"
